### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

### ISSUE THREAD

**Issue by gitkrsna** [bitcrowd/rag_time#4]
I am getting below error while running `python ingest-code.py`

`Traceback (most recent call last):
  File "/Users/kky/Desktop/apps/rag_time/ingest-code.py", line 84, in <module>
    create_vector_database()
  File "/Users/kky/Desktop/apps/rag_time/ingest-code.py", line 36, in create_vector_database
    chunked_documents.extend(chunk_code())
                             ^^^^^^^^^^^^
  File "/Users/kky/Desktop/apps/rag_time/ingest-code.py", line 61, in chunk_code
    loaded_documents = loader.load()
                       ^^^^^^^^^^^^^
  File "/Users/kky/Desktop/apps/rag_time/.venv/lib/python3.11/site-packages/langchain_core/document_loaders/base.py", line 29, in load
    return list(self.lazy_load())
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kky/Desktop/apps/rag_time/.venv/lib/python3.11/site-packages/langchain_community/document_loaders/generic.py", line 116, in lazy_load
    yield from self.blob_parser.lazy_parse(blob)
  File "/Users/kky/Desktop/apps/rag_time/.venv/lib/python3.11/site-packages/langchain_community/document_loaders/parsers/language/language_parser.py", line 191, in lazy_parse
    code = blob.as_string()
           ^^^^^^^^^^^^^^^^
  File "/Users/kky/Desktop/apps/rag_time/.venv/lib/python3.11/site-packages/langchain_core/document_loaders/blob_loaders.py", line 74, in as_string
    return f.read()
           ^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
`

**Comment by xhr15** [comment]
Hi @gitkrsna, this is a classic. The file you are trying to read is in a different encoding, very likely 'latin-1'.


You would need to change code / explore options to the `language_parser.py", which is a langchain module. You can also use other ways to open the files for ingestion, sth like:

```
        try:
            ...
        except UnicodeDecodeError:
            print(f"Error reading file {file_path}. Trying with 'latin-1' encoding.")
            with open(... encoding='latin-1') as file:
  ```          
  This is a bit outside the scope of this demo project, but feel free to open a PR on this. Alternatively, you can make sure that your files are all in 'utf-8'. 
  
  I am closing this issue for now
